import type { Metadata } from "next";
import "../(main)/globals.css";

import { HeroUIProvider } from "@heroui/react";
import SliderRegister from "@/components/authComponent/SliderRegister";
import { ThemeProvider } from "next-themes";
import DarkSwitcher from "@/components/HomeContainer/HeaderComponent-01/DarkSwitcher";
import ProviderNextUI from "../RootLayout";
export const metadata: Metadata = {
  title: "MARFA-NEXT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="RTL">
      <body className="p-4  dark:bg-gray-800 h-screen max-w-[1920px] overflow-x-hidden">
        <ProviderNextUI>
        {/* <HeroUIProvider> */}
          <ThemeProvider attribute="class" defaultTheme="dark">
             <DarkSwitcher />
            <div className="flex w-full md:flex-row flex-col  justify-between items-center gap-8 overflow-hidden">
              {children}
             <SliderRegister />
            </div>
          </ThemeProvider>
        {/* </HeroUIProvider> */}
        </ProviderNextUI>
      </body>
    </html>
  );
}

// import AuthContainer from "@/components/auth/container";
// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "ورود یا ثبت‌نام | ",
//   description: "به حساب کاربری خود وارد شوید یا یک حساب جدید ایجاد کنید.",
//   keywords: ["ورود", "ثبت‌ نام", "دلتا", "احراز هویت"],
// };

// export default function AuthLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <div>
//       {/* <AuthContainer> */}
//         {children}
//         {/* </AuthContainer> */}
//     </div>
//   );
// }
