import type { Metadata } from "next";
import "../(main)/globals.css";

import { HeroUIProvider } from "@heroui/react";
import SliderRegister from "@/components/authComponent/SliderRegister";
import { ThemeProvider } from "next-themes";
import DarkSwitcher from "@/components/HomeContainer/HeaderComponent-01/DarkSwitcher";
export const metadata: Metadata = {
  title: "MARFA-NEXT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="RTL">
      <body className="bg-white mx-auto  dark:bg-gray-900  px-4 py-4 max-w-screen-2xl overflow-x-hidden">
        <HeroUIProvider>
          <ThemeProvider attribute="class" defaultTheme="dark">
            <DarkSwitcher />
            <div className="flex md:flex-row flex-col justify-center items-center border-2 shadow-lg md:py-2 md:mt-10 gap-8 overflow-hidden">
              {children}
              <div className="hidden md:flex justify-center items-center md:p-2">
                <SliderRegister />
              </div>
            </div>
          </ThemeProvider>
        </HeroUIProvider>
      </body>
    </html>
  );
}

// import AuthContainer from "@/components/auth/container";
// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "ورود یا ثبت‌نام | ",
//   description: "به حساب کاربری خود وارد شوید یا یک حساب جدید ایجاد کنید.",
//   keywords: ["ورود", "ثبت‌ نام", "دلتا", "احراز هویت"],
// };

// export default function AuthLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <div>
//       {/* <AuthContainer> */}
//         {children}
//         {/* </AuthContainer> */}
//     </div>
//   );
// }
