import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/HomeContainer/HeaderComponent/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <header className="flex items-center justify-between w-full overflow-hidden">
          <Header />
        </header>
        {children}
        <footer className="flex flex-col gap-12 bg-[#2841e3] mx-auto px-7 py-8 rounded-3xl w-[95%]">
          {/* <FooterContainer /> */}
          footer
        </footer>
       
      </body>
    </html>
  );
}
